default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: g2-rails-practice-new_task-list-development

test:
  <<: *default
  database: g2-rails-practice-new_task-list-test
